import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, Text, View, StyleSheet } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import CandidateBottomNav from "../components/CandidateBottomNav";
import { API_URL } from "../config/api";
import { authHeaders } from "../config/session";
import { colors } from "../theme/colors";

const tabs = ["Todas", "Postulado", "CV Visto", "En proceso", "Finalista"];
const normalizeStatus = (value) => String(value || "Postulado").toLowerCase();
const progressFor = (value) => { const status = normalizeStatus(value); if (status.includes("finalista")) return 100; if (status.includes("proceso")) return 75; if (status.includes("visto")) return 50; return 25; };
const statusSteps = ["Postulado", "CV Visto", "En proceso", "Finalista"];

export default function ApplicationsScreen({ navigation }) {
  const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [activeTab, setActiveTab] = useState("Todas");
  const loadApplications = useCallback(async (isRefresh = false) => { if (isRefresh) setRefreshing(true); else setLoading(true); try { const res = await fetch(`${API_URL}/applications`, { headers: authHeaders() }); if (!res.ok) throw new Error(); setApplications(await res.json()); } catch (_error) { if (!isRefresh) setApplications([]); } finally { if (isRefresh) setRefreshing(false); else setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { loadApplications(); }, [loadApplications]));
  const filtered = useMemo(() => activeTab === "Todas" ? applications : applications.filter((item) => normalizeStatus(item.status) === activeTab.toLowerCase()), [applications, activeTab]);

  return <View style={styles.screen}>
    <ScrollView contentContainerStyle={styles.container} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => loadApplications(true)} />}>
      <Text style={styles.headerTitle} accessibilityRole="header">Mis postulaciones</Text>
      <Text style={styles.subtitle}>Sigue cada etapa de tu proceso y conoce tu Match integral.</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{tabs.map((tab) => <Pressable key={tab} onPress={() => setActiveTab(tab)} style={[styles.tab, activeTab === tab && styles.tabActive]} accessibilityRole="tab" accessibilityState={{ selected: activeTab === tab }}><Text style={[styles.tabText, activeTab === tab && styles.tabTextActive]}>{tab}</Text></Pressable>)}</ScrollView>
      {loading && <ActivityIndicator color={colors.primary} style={{ marginTop: 18 }} />}
      {!loading && filtered.map((application) => { const progress = progressFor(application.status); const currentStep = Math.max(0, Math.min(3, Math.ceil(progress / 25) - 1)); return <View key={application._id} style={styles.card} accessible accessibilityLabel={`${application.jobId?.title || "Oferta"}, ${application.jobId?.companyId?.name || "Empresa"}, Match ${Number(application.matchScore ?? 0)}%, ${application.status || "Postulado"}`}>
        <Text style={styles.job}>{application.jobId?.title || "Oferta"}</Text><Text style={styles.company}>{application.jobId?.companyId?.name || "Empresa"}</Text>
        <View style={styles.statusRow}><View style={styles.ring}><Text style={styles.ringText}>{Number(application.matchScore ?? 0)}%</Text><Text style={styles.ringLabel}>MATCH</Text></View><View style={{ flex: 1, marginLeft: 18 }}><Text style={styles.status}>{application.status || "Postulado"}</Text><Text style={styles.date}>{application.createdAt ? new Date(application.createdAt).toLocaleDateString() : ""}</Text><Text style={styles.candidates}>{application.candidateCount ? `${application.candidateCount} candidatos postulados` : "Postulación registrada"}</Text></View></View>
        <Text style={styles.progressTitle}>Progreso de la postulación</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%` }]} /></View><View style={styles.steps}>{statusSteps.map((step, index) => <View key={step} style={styles.step}><View style={[styles.stepDot, index <= currentStep && styles.stepDotActive]} /><Text style={[styles.stepText, index <= currentStep && styles.stepTextActive]}>{step}</Text></View>)}</View>
        {application.matchBreakdown && Object.keys(application.matchBreakdown).length > 0 && <View style={styles.breakdownBox}><Text style={styles.breakdownTitle}>¿Por qué este Match?</Text>{Object.entries(application.matchBreakdown).map(([key, value]) => <Text key={key} style={styles.breakdown}>• {{ skills: "Habilidades", experience: "Experiencia", education: "Educación", modality: "Modalidad", accessibility: "Accesibilidad" }[key] || key}: {value}%</Text>)}</View>}
      </View>; })}
      {!loading && !filtered.length && <View style={styles.empty}><Text style={styles.emptyTitle}>No tienes postulaciones en esta categoría</Text><Text style={styles.emptyText}>Explora las oportunidades disponibles y encuentra tu próximo empleo.</Text></View>}
    </ScrollView><CandidateBottomNav navigation={navigation} active="applications" />
  </View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, container: { flexGrow: 1, paddingBottom: 105 }, headerTitle: { color: colors.white, backgroundColor: colors.secondary, textAlign: "center", fontSize: 28, paddingVertical: 22 }, subtitle: { paddingHorizontal: 18, paddingTop: 14, color: colors.text, fontSize: 15 }, tabs: { padding: 16, gap: 10 }, tab: { backgroundColor: "#E6EEF9", borderRadius: 28, paddingHorizontal: 22, paddingVertical: 12 }, tabActive: { backgroundColor: colors.secondary }, tabText: { fontSize: 17, color: colors.text }, tabTextActive: { color: colors.white, fontWeight: "800" }, card: { marginHorizontal: 18, marginBottom: 16, padding: 20, borderRadius: 20, backgroundColor: colors.white, elevation: 4 }, job: { fontWeight: "800", fontSize: 22, color: colors.text, lineHeight: 29 }, company: { fontSize: 18, color: "#64748B", marginTop: 8 }, statusRow: { flexDirection: "row", alignItems: "center", marginTop: 20 }, ring: { width: 82, height: 82, borderRadius: 41, borderWidth: 8, borderColor: colors.secondary, alignItems: "center", justifyContent: "center" }, ringText: { fontWeight: "800", color: colors.secondary }, ringLabel: { fontSize: 9, fontWeight: "800", color: "#64748B" }, status: { fontSize: 18, fontWeight: "800", color: colors.secondary }, date: { fontSize: 16, color: colors.text, marginTop: 4 }, candidates: { fontSize: 15, color: "#64748B", marginTop: 5 }, progressTitle: { marginTop: 20, fontWeight: "800", color: colors.primary }, progressTrack: { height: 9, borderRadius: 5, backgroundColor: "#E2E8F0", marginTop: 9, overflow: "hidden" }, progressFill: { height: 9, borderRadius: 5, backgroundColor: colors.primary }, steps: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 }, step: { flex: 1, alignItems: "center" }, stepDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#CBD5E1" }, stepDotActive: { backgroundColor: colors.primary }, stepText: { fontSize: 10, color: "#64748B", textAlign: "center", marginTop: 4 }, stepTextActive: { color: colors.primary, fontWeight: "800" }, breakdownBox: { marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: "#E2E8F0" }, breakdownTitle: { fontWeight: "800", color: colors.primary, marginBottom: 5 }, breakdown: { color: colors.text, marginTop: 2 }, empty: { margin: 28, alignItems: "center" }, emptyTitle: { fontSize: 20, fontWeight: "800", color: colors.text, textAlign: "center" }, emptyText: { marginTop: 10, fontSize: 16, color: "#64748B", textAlign: "center" }
});
