import React, { useState } from "react";
import { Alert, ScrollView, Text, StyleSheet, View } from "react-native";
import AccessibleButton from "../components/AccessibleButton";
import { API_URL } from "../config/api";
import { authHeaders, getSessionRole } from "../config/session";
import { colors } from "../theme/colors";

const criteriaLabels = { skills: "Habilidades", experience: "Experiencia", education: "Educación", modality: "Modalidad", accessibility: "Accesibilidad" };

export default function JobDetailScreen({ route, navigation }) {
  const { job } = route.params || {};
  const [applied, setApplied] = useState(false); const [role, setRole] = useState(null); const [loading, setLoading] = useState(false); const [checkingApplication, setCheckingApplication] = useState(true); const [applicationMatch, setApplicationMatch] = useState(job?.score);
  React.useEffect(() => { let mounted = true; const checkApplication = async () => { try { const sessionRole = await getSessionRole(); if (!mounted) return; setRole(sessionRole); if (sessionRole !== "candidate" || !job?._id) return; const response = await fetch(API_URL + "/applications", { headers: authHeaders() }); if (!response.ok) return; const applications = await response.json(); const existing = applications.find((item) => item.jobId?._id === job._id || item.jobId === job._id); if (existing && mounted) { setApplied(true); setApplicationMatch(existing.matchScore); } } catch (_error) {} finally { if (mounted) setCheckingApplication(false); } }; checkApplication(); return () => { mounted = false; }; }, [job?._id]);
  if (!job) return <Text style={styles.empty}>No se encontró la oferta.</Text>;
  const apply = async () => { if (role !== "candidate" || applied || checkingApplication) return; setLoading(true); try { const response = await fetch(`${API_URL}/applications`, { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ jobId: job._id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "No se pudo registrar la postulación"); setApplied(true); setApplicationMatch(data.matchScore); Alert.alert("Postulación registrada", `Tu postulación fue guardada. Match integral: ${data.matchScore}%`); } catch (error) { Alert.alert("Error", error.message); } finally { setLoading(false); } };
  const match = Number(applicationMatch ?? job.score ?? 0); const breakdown = job.breakdown || {}; const bestCriteria = Object.entries(breakdown).sort((a, b) => Number(b[1]) - Number(a[1])).slice(0, 2); const missing = job.missingSkills || [];
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>{job.title}</Text><Text style={styles.company}>🏢 {job.companyId?.name || "Empresa"}</Text>{applicationMatch !== undefined && <View style={styles.matchCard}><View style={styles.matchHeader}><View><Text style={styles.matchLabel}>Match integral</Text><Text style={styles.matchExplanation}>{match >= 80 ? "Excelente coincidencia" : match >= 60 ? "Buena coincidencia" : "Hay oportunidades para mejorar"}</Text></View><Text style={styles.match}>{match}%</Text></View><Text style={styles.whyTitle}>¿Por qué encaja contigo?</Text>{bestCriteria.map(([key, value]) => <View key={key} style={styles.metricRow}><Text style={styles.metricLabel}>{criteriaLabels[key] || key}</Text><View style={styles.metricTrack}><View style={[styles.metricFill, { width: `${Math.max(0, Math.min(100, Number(value) || 0))}%` }]} /></View><Text style={styles.metricValue}>{value}%</Text></View>)}{missing.length > 0 ? <Text style={styles.warning}>⚠️ Para mejorar tu compatibilidad: {missing.join(" · ")}</Text> : <Text style={styles.success}>✓ Tu perfil cubre las habilidades principales de esta oferta.</Text>}</View>}
  <Text style={styles.section}>Información de la oferta</Text><Text style={styles.text}>Área: {job.area}</Text><Text style={styles.text}>Modalidad: {job.modality || "No especificada"}</Text>{job.experienceRequired !== undefined && <Text style={styles.text}>Experiencia mínima: {job.experienceRequired} años</Text>}{job.educationRequired && <Text style={styles.text}>Formación requerida: {job.educationRequired}</Text>}
  <Text style={styles.section}>Requisitos</Text><Text style={styles.text}>{(job.requirements || []).join(" · ") || "No especificados"}</Text><View style={styles.accessibilityCard}><Text style={styles.accessibilityTitle}>♿ Accesibilidad declarada</Text><Text style={styles.text}>{(job.accessibility || []).join(" · ") || "La empresa no ha declarado ajustes específicos; puedes coordinarlos durante el proceso."}</Text>{job.matchedAccessibility?.length > 0 && <Text style={styles.success}>✓ Compatible con tu perfil: {job.matchedAccessibility.join(" · ")}</Text>}</View>
  <AccessibleButton title={applied ? "✓ Postulación enviada" : checkingApplication ? "Verificando postulación..." : loading ? "Enviando..." : "📌 Postular"} onPress={apply} disabled={role !== "candidate" || applied || loading || checkingApplication} /><AccessibleButton title="Volver a empleos" type="secondary" onPress={() => navigation.goBack()} /></ScrollView>;
}
const styles = StyleSheet.create({ container: { flexGrow: 1, padding: 24, backgroundColor: colors.white, paddingBottom: 40 }, title: { fontSize: 30, fontWeight: "800", color: colors.primary, marginBottom: 8 }, company: { fontSize: 17, color: colors.text }, section: { fontSize: 18, fontWeight: "800", color: colors.secondary, marginTop: 20, marginBottom: 8 }, text: { fontSize: 16, lineHeight: 24, color: colors.text }, matchCard: { marginTop: 20, padding: 18, borderRadius: 16, backgroundColor: colors.background }, matchHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, matchLabel: { fontSize: 16, fontWeight: "700", color: colors.text }, matchExplanation: { marginTop: 3, color: colors.secondary, fontWeight: "800" }, match: { fontSize: 36, fontWeight: "800", color: colors.secondary }, whyTitle: { marginTop: 16, fontSize: 17, fontWeight: "800", color: colors.primary }, metricRow: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8 }, metricLabel: { width: 92, fontSize: 12 }, metricTrack: { flex: 1, height: 8, borderRadius: 4, backgroundColor: "#E2E8F0", overflow: "hidden" }, metricFill: { height: 8, borderRadius: 4, backgroundColor: colors.primary }, metricValue: { width: 38, fontSize: 12, fontWeight: "800", textAlign: "right" }, warning: { marginTop: 12, color: "#92400E", lineHeight: 21 }, success: { marginTop: 12, color: "#047857", lineHeight: 21, fontWeight: "600" }, accessibilityCard: { marginTop: 20, padding: 16, borderRadius: 16, backgroundColor: "#F8FAFC", borderWidth: 1, borderColor: "#E2E8F0" }, accessibilityTitle: { fontSize: 18, fontWeight: "800", color: colors.secondary, marginBottom: 7 }, empty: { padding: 24 } });
