import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View, StyleSheet } from "react-native";
import { Picker } from "@react-native-picker/picker";
import AccessibleButton from "../components/AccessibleButton";
import CandidateBottomNav from "../components/CandidateBottomNav";
import { API_URL } from "../config/api";
import { colors } from "../theme/colors";
import { authHeaders, getSessionRole } from "../config/session";
import { font, horizontalPadding, rs } from "../theme/responsive";

const criteriaLabels = { skills: "Habilidades", experience: "Experiencia", education: "Educación", modality: "Modalidad", accessibility: "Accesibilidad" };
const sortOptions = ["Match más alto", "Más recientes", "Título A-Z"];

export default function JobsScreen({ navigation }) {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [keyword, setKeyword] = useState(""); const [area, setArea] = useState("Todas"); const [modality, setModality] = useState("Todas"); const [sortBy, setSortBy] = useState("Match más alto"); const [accessibilityOnly, setAccessibilityOnly] = useState(false); const [minSalary, setMinSalary] = useState(""); const [showFilters, setShowFilters] = useState(false); const [isCandidate, setIsCandidate] = useState(false);
  useEffect(() => { const loadJobs = async () => { try { const role = await getSessionRole(); setIsCandidate(role === "candidate"); const endpoint = role === "candidate" ? `${API_URL}/profile/matches` : `${API_URL}/company/jobs`; const response = await fetch(endpoint, { headers: authHeaders() }); const data = await response.json(); setJobs(role === "candidate" ? (data.matches || []) : (response.ok ? data : [])); } catch (_error) { setJobs([]); } finally { setLoading(false); } }; loadJobs(); }, []);
  const toggleFavorite = async (jobId, current) => { try { const response = await fetch(`${API_URL}/profile/favorites/${jobId}`, { method: current ? "DELETE" : "POST", headers: authHeaders() }); if (!response.ok) return; setJobs((items) => items.map((job) => job._id === jobId ? { ...job, isFavorite: !current } : job)); } catch (_error) {} };
  const filteredJobs = useMemo(() => { const requestedSalary = Number(minSalary); const result = jobs.filter((job) => { const text = `${job.title} ${job.companyId?.name || ""} ${(job.requirements || []).join(" ")}`.toLowerCase(); const hasAccessibility = Array.isArray(job.accessibility) && job.accessibility.length > 0; const salaryOk = !minSalary || (Number.isFinite(requestedSalary) && (job.salaryMax === undefined || Number(job.salaryMax) >= requestedSalary)); return (!keyword.trim() || text.includes(keyword.toLowerCase().trim())) && (area === "Todas" || job.area === area) && (modality === "Todas" || job.modality === modality) && (!accessibilityOnly || hasAccessibility) && salaryOk; }); return [...result].sort((a, b) => sortBy === "Match más alto" ? Number(b.score ?? 0) - Number(a.score ?? 0) : sortBy === "Título A-Z" ? String(a.title || "").localeCompare(String(b.title || "")) : new Date(b.createdAt || 0) - new Date(a.createdAt || 0)); }, [jobs, keyword, area, modality, sortBy, accessibilityOnly, minSalary]);
  const areas = ["Todas", ...new Set(jobs.map((job) => job.area).filter(Boolean))]; const modalities = ["Todas", ...new Set(jobs.map((job) => job.modality).filter(Boolean))];
  return <View style={styles.screen}>
    <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
      <Text style={styles.headerTitle}>Buscar empleos</Text>
      <Text style={styles.subtitle}>Encuentra oportunidades y prioriza las que mejor encajan contigo.</Text>
      <TextInput style={styles.input} placeholder="Cargo, habilidad o empresa" placeholderTextColor="#64748B" value={keyword} onChangeText={setKeyword} accessibilityLabel="Buscar empleo" />
      <View style={styles.quickRow}>
        <View style={styles.quickChip}><Text style={styles.quickText} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.72}>✦ Match</Text></View>
        <Pressable style={[styles.quickChip, accessibilityOnly && styles.quickChipActive]} onPress={() => setAccessibilityOnly((value) => !value)} accessibilityRole="checkbox" accessibilityState={{ checked: accessibilityOnly }}><Text style={[styles.quickText, accessibilityOnly && styles.quickTextActive]} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.68}>♿ Accesibles</Text></Pressable>
        <Pressable style={styles.filterButton} onPress={() => setShowFilters((value) => !value)}><Text style={styles.filterButtonText} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.7}>{showFilters ? "Ocultar" : "Filtros"}</Text></Pressable>
      </View>
      {showFilters && <View style={styles.filterPanel}>
        <Text style={styles.label}>Área profesional</Text><View style={styles.pickerBox}><Picker selectedValue={area} onValueChange={setArea}>{areas.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker></View>
        <Text style={styles.label}>Modalidad</Text><View style={styles.pickerBox}><Picker selectedValue={modality} onValueChange={setModality}>{modalities.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker></View>
        <Text style={styles.label}>Salario mínimo mensual (S/)</Text><TextInput style={styles.inputFilter} placeholder="Ej. 1500" placeholderTextColor="#94A3B8" value={minSalary} onChangeText={(value) => setMinSalary(value.replace(/[^0-9]/g, ""))} keyboardType="numeric" accessibilityLabel="Salario mínimo mensual" />
        <Text style={styles.label}>Ordenar por</Text><View style={styles.pickerBox}><Picker selectedValue={sortBy} onValueChange={setSortBy}>{sortOptions.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker></View>
      </View>}
      {!showFilters && <Text style={styles.filterSummary}>Orden: {sortBy} · {modality === "Todas" ? "Todas las modalidades" : modality}{minSalary ? ` · Desde S/ ${minSalary}` : ""}</Text>}
      {loading ? <ActivityIndicator color={colors.primary} style={{ marginTop: rs(18) }} /> : <Text style={styles.results}>{filteredJobs.length} oportunidades encontradas</Text>}
      {filteredJobs.map((job) => <View key={job._id} style={styles.card}>
        <View style={styles.header}><View style={{ flex: 1, minWidth: 0 }}><Text style={styles.jobTitle} numberOfLines={2}>{job.title}</Text><Text style={styles.company} numberOfLines={1}>{job.companyId?.name || "Empresa"}</Text></View>{isCandidate && <Pressable onPress={() => toggleFavorite(job._id, !!job.isFavorite)} accessibilityRole="button" accessibilityLabel={job.isFavorite ? `Quitar ${job.title} de favoritos` : `Guardar ${job.title} en favoritos`} hitSlop={10}><Text style={[styles.heart, job.isFavorite && styles.heartActive]}> {job.isFavorite ? "♥" : "♡"}</Text></Pressable>}</View>
        <View style={styles.metaRow}><Text style={styles.match} numberOfLines={1}>{job.score !== undefined ? `${job.score}% Match` : "Oferta"}</Text>{(job.salaryMin !== undefined || job.salaryMax !== undefined) && <Text style={styles.salary} numberOfLines={1}>S/ {job.salaryMin !== undefined ? Number(job.salaryMin).toLocaleString() : "Desde"}{job.salaryMax !== undefined ? ` – ${Number(job.salaryMax).toLocaleString()}` : ""}</Text>}</View>
        <Text style={styles.meta} numberOfLines={2}>💼 {job.area || "Área no especificada"} · 🏠 {job.modality || "No especificada"}</Text>
        <View style={styles.accessibilityBox}><Text style={styles.accessibilityTitle}>♿ Accesibilidad</Text><Text style={styles.accessibilityText}>{(job.accessibility || []).join(" · ") || "Ajustes por coordinar"}</Text></View>
        {job.score !== undefined && <><Text style={styles.sectionTitle}>¿Por qué encaja contigo?</Text>{Object.entries(job.breakdown || {}).map(([key, value]) => <View key={key} style={styles.metricRow}><Text style={styles.metricLabel} numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.72}>{criteriaLabels[key] || key}</Text><View style={styles.metricTrack}><View style={[styles.metricFill, { width: `${Math.max(0, Math.min(100, Number(value) || 0))}%` }]} /></View><Text style={styles.metricValue}>{value}%</Text></View>)}{job.missingSkills?.length > 0 && <Text style={styles.warning}>⚠️ Te faltan: {job.missingSkills.join(" · ")}</Text>}{job.matchedSkills?.length > 0 && <Text style={styles.good}>✓ Coincides en: {job.matchedSkills.join(" · ")}</Text>}{job.matchedAccessibility?.length > 0 && <Text style={styles.good}>✓ Ajustes compatibles: {job.matchedAccessibility.join(" · ")}</Text>}</>}
        <AccessibleButton title="Ver oferta" onPress={() => navigation.navigate("JobDetail", { job })} />
      </View>)}
      {!loading && !filteredJobs.length && <Text style={styles.empty}>No encontramos ofertas con estos filtros.</Text>}
    </ScrollView><CandidateBottomNav navigation={navigation} active="search" />
  </View>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  container: { flexGrow: 1, paddingBottom: rs(108, 100, 118), backgroundColor: colors.background },
  headerTitle: { color: colors.text, backgroundColor: colors.background, textAlign: "left", fontSize: font(29), fontWeight: "800", paddingHorizontal: horizontalPadding, paddingTop: rs(22), paddingBottom: rs(3) },
  subtitle: { fontSize: font(15), lineHeight: font(21), color: "#64748B", marginHorizontal: horizontalPadding, marginBottom: rs(16) },
  input: { marginHorizontal: horizontalPadding, borderWidth: 1, borderColor: "#CBD5E1", backgroundColor: colors.white, borderRadius: rs(15, 12, 18), paddingHorizontal: rs(15), paddingVertical: rs(13, 10, 15), fontSize: font(16), minHeight: rs(50, 46, 54) },
  quickRow: { flexDirection: "row", alignItems: "center", gap: rs(7, 5, 9), marginHorizontal: horizontalPadding, marginTop: rs(12), minWidth: 0 },
  quickChip: { flex: 1, minWidth: 0, minHeight: rs(44, 40, 48), paddingVertical: rs(10, 8, 12), paddingHorizontal: rs(7, 5, 9), borderRadius: rs(14, 12, 16), backgroundColor: "#EDE9FE", alignItems: "center", justifyContent: "center" },
  quickChipActive: { backgroundColor: colors.primary }, quickText: { color: colors.primary, fontSize: font(12), fontWeight: "800" }, quickTextActive: { color: colors.white },
  filterButton: { flexShrink: 1, minWidth: rs(68, 62, 76), minHeight: rs(44, 40, 48), paddingVertical: rs(10, 8, 12), paddingHorizontal: rs(9, 7, 12), borderRadius: rs(14, 12, 16), backgroundColor: colors.white, borderWidth: 1, borderColor: "#CBD5E1", alignItems: "center", justifyContent: "center" }, filterButtonText: { color: colors.text, fontSize: font(12), fontWeight: "800" },
  filterPanel: { marginHorizontal: horizontalPadding, marginTop: rs(10), padding: rs(12, 10, 14), borderRadius: rs(16, 14, 18), backgroundColor: colors.white, borderWidth: 1, borderColor: "#E2E8F0" }, label: { marginTop: rs(7), marginBottom: rs(3), fontWeight: "700", color: colors.text, fontSize: font(13) }, pickerBox: { borderWidth: 1, borderColor: "#E2E8F0", borderRadius: rs(10, 9, 12), overflow: "hidden", backgroundColor: "#F8FAFC" }, inputFilter: { borderWidth: 1, borderColor: "#E2E8F0", borderRadius: rs(10, 9, 12), paddingHorizontal: rs(10), paddingVertical: rs(9, 8, 11), fontSize: font(14), minHeight: rs(44, 40, 48) },
  filterSummary: { marginHorizontal: horizontalPadding, marginTop: rs(10), color: colors.primary, fontSize: font(12), fontWeight: "700" }, results: { marginHorizontal: horizontalPadding, marginTop: rs(15), marginBottom: rs(2), fontWeight: "700", color: colors.text, fontSize: font(14) },
  card: { borderRadius: rs(18, 15, 20), padding: rs(17, 14, 19), marginHorizontal: rs(18, 14, 22), marginTop: rs(12, 10, 14), backgroundColor: colors.white, elevation: 3, gap: rs(8, 6, 10) },
  header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: rs(10, 8, 12) }, jobTitle: { fontSize: font(20), lineHeight: font(24), fontWeight: "800", color: colors.text }, company: { fontSize: font(15), color: "#64748B", marginTop: rs(4) }, heart: { fontSize: font(31), color: colors.primary }, heartActive: { color: colors.primary },
  metaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: rs(8) }, match: { maxWidth: "48%", alignSelf: "flex-start", paddingHorizontal: rs(10), paddingVertical: rs(6), borderRadius: rs(14, 12, 16), backgroundColor: "#EDE9FE", color: colors.primary, fontWeight: "800", fontSize: font(12) }, salary: { flexShrink: 1, color: colors.success, fontWeight: "800", fontSize: font(14), textAlign: "right" }, meta: { color: colors.text, fontSize: font(14), lineHeight: font(20) },
  accessibilityBox: { padding: rs(11, 9, 13), borderRadius: rs(12, 10, 14), backgroundColor: "#F8FAFC" }, accessibilityTitle: { fontWeight: "800", color: colors.secondary, marginBottom: rs(3), fontSize: font(14) }, accessibilityText: { color: colors.text, fontSize: font(13), lineHeight: font(18) }, sectionTitle: { marginTop: rs(5), fontWeight: "800", color: colors.primary, fontSize: font(14) }, metricRow: { flexDirection: "row", alignItems: "center", gap: rs(7, 5, 8), minWidth: 0 }, metricLabel: { width: rs(82, 68, 92), fontSize: font(11) }, metricTrack: { flex: 1, height: rs(7, 6, 8), borderRadius: 4, backgroundColor: "#E2E8F0", overflow: "hidden" }, metricFill: { height: rs(7, 6, 8), borderRadius: 4, backgroundColor: colors.primary }, metricValue: { width: rs(35, 30, 40), fontSize: font(11), fontWeight: "800", textAlign: "right" }, warning: { marginTop: rs(4), color: "#92400E", fontSize: font(13), lineHeight: font(18) }, good: { color: colors.success, fontSize: font(13), lineHeight: font(18) }, empty: { marginHorizontal: horizontalPadding, marginTop: rs(24), color: colors.text, textAlign: "center", fontSize: font(14) }
});
