import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View, StyleSheet } from "react-native";
import { Picker } from "@react-native-picker/picker";
import AccessibleButton from "../components/AccessibleButton";
import CandidateBottomNav from "../components/CandidateBottomNav";
import { API_URL } from "../config/api";
import { colors } from "../theme/colors";
import { authHeaders, getSessionRole } from "../config/session";

const criteriaLabels = { skills: "Habilidades", experience: "Experiencia", education: "Educación", modality: "Modalidad", accessibility: "Accesibilidad" };

export default function JobsScreen({ navigation }) {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [keyword, setKeyword] = useState(""); const [area, setArea] = useState("Todas"); const [modality, setModality] = useState("Todas"); const [isCandidate, setIsCandidate] = useState(false);
  useEffect(() => { const loadJobs = async () => { try { const role = await getSessionRole(); setIsCandidate(role === "candidate"); const endpoint = role === "candidate" ? `${API_URL}/profile/matches` : `${API_URL}/company/jobs`; const response = await fetch(endpoint, { headers: authHeaders() }); const data = await response.json(); setJobs(role === "candidate" ? (data.matches || []) : (response.ok ? data : [])); } catch (_error) { setJobs([]); } finally { setLoading(false); } }; loadJobs(); }, []);
  const toggleFavorite = async (jobId, current) => { try { const response = await fetch(`${API_URL}/profile/favorites/${jobId}`, { method: current ? "DELETE" : "POST", headers: authHeaders() }); if (!response.ok) return; setJobs((items) => items.map((job) => job._id === jobId ? { ...job, isFavorite: !current } : job)); } catch (_error) {} };
  const filteredJobs = useMemo(() => jobs.filter((job) => { const text = `${job.title} ${job.companyId?.name || ""} ${(job.requirements || []).join(" ")}`.toLowerCase(); return (!keyword.trim() || text.includes(keyword.toLowerCase().trim())) && (area === "Todas" || job.area === area) && (modality === "Todas" || job.modality === modality); }), [jobs, keyword, area, modality]);
  const areas = ["Todas", ...new Set(jobs.map((job) => job.area).filter(Boolean))]; const modalities = ["Todas", ...new Set(jobs.map((job) => job.modality).filter(Boolean))];
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.container}><Text style={styles.headerTitle}>Buscar empleos</Text><Text style={styles.subtitle}>Oportunidades publicadas por empresas inclusivas.</Text><TextInput style={styles.input} placeholder="Cargo, habilidad o empresa" value={keyword} onChangeText={setKeyword} accessibilityLabel="Buscar empleo" /><Text style={styles.label}>Área profesional</Text><Picker selectedValue={area} onValueChange={setArea}>{areas.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker><Text style={styles.label}>Modalidad</Text><Picker selectedValue={modality} onValueChange={setModality}>{modalities.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker>{loading ? <ActivityIndicator color={colors.primary} /> : <Text style={styles.results}>{filteredJobs.length} oportunidades encontradas</Text>}{filteredJobs.map((job) => <View key={job._id} style={styles.card}><View style={styles.header}><Text style={styles.jobTitle}>{job.title}</Text>{isCandidate && <Pressable onPress={() => toggleFavorite(job._id, !!job.isFavorite)} accessibilityRole="button" accessibilityLabel={job.isFavorite ? `Quitar ${job.title} de favoritos` : `Guardar ${job.title} en favoritos`} hitSlop={10}><Text style={[styles.heart, job.isFavorite && styles.heartActive]}>{job.isFavorite ? "♥" : "♡"}</Text></Pressable>}{job.score !== undefined && <Text style={styles.match}>{job.score}%</Text>}</View><Text>🏢 {job.companyId?.name || "Empresa"}</Text><Text>💼 {job.area} · 🏠 {job.modality}</Text><Text>♿ {(job.accessibility || []).join(" · ") || "Ajustes por coordinar"}</Text>{job.score !== undefined && <><Text style={styles.sectionTitle}>Desglose del Match</Text>{Object.entries(job.breakdown || {}).map(([key, value]) => <Text key={key} style={styles.breakdown}>• {criteriaLabels[key] || key}: {value}%</Text>)}<Text style={styles.sectionTitle}>Coincidencias</Text><Text>✓ Habilidades: {(job.matchedSkills || []).join(" · ") || "Ninguna"}</Text>{job.missingSkills?.length > 0 && <Text>⚠️ Habilidades faltantes: {job.missingSkills.join(" · ")}</Text>}{job.matchedAccessibility?.length > 0 && <Text>✓ Accesibilidad: {job.matchedAccessibility.join(" · ")}</Text>}</>}<AccessibleButton title={`Ver oferta: ${job.title}`} onPress={() => navigation.navigate("JobDetail", { job })} /></View>)}{!loading && !filteredJobs.length && <Text style={styles.empty}>No encontramos ofertas con estos filtros.</Text>}</ScrollView><CandidateBottomNav navigation={navigation} active="search" /></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, container: { flexGrow: 1, paddingBottom: 105, backgroundColor: colors.white }, headerTitle: { color: colors.white, backgroundColor: colors.secondary, textAlign: "center", fontSize: 28, paddingVertical: 22, marginBottom: 18 }, subtitle: { fontSize: 16, color: colors.text, marginHorizontal: 24, marginBottom: 18 }, input: { marginHorizontal: 24, borderWidth: 1, borderColor: "#CBD5E1", borderRadius: 14, padding: 14, fontSize: 16 }, label: { marginTop: 10, marginHorizontal: 24, fontWeight: "700", color: colors.text }, results: { margin: 16, fontWeight: "700", color: colors.secondary }, card: { borderRadius: 18, padding: 18, margin: 12, backgroundColor: colors.white, elevation: 3, gap: 8 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, jobTitle: { flex: 1, fontSize: 20, fontWeight: "800", color: colors.text }, heart: { fontSize: 34, color: colors.secondary }, heartActive: { color: colors.primary }, match: { fontSize: 24, fontWeight: "800", color: colors.secondary }, sectionTitle: { marginTop: 8, fontWeight: "800", color: colors.primary }, breakdown: { fontSize: 15 }, empty: { margin: 24, color: colors.text } });
